### ISSUE TITLE
Question about "PostCSS Has Pseudo" for building

### ISSUE THREAD

**Issue by Annie972297** [csstools/postcss-plugins#1504] opened 2024-11-07 02:44 UTC
Hi, I'm using "PostCSS Has Pseudo" in a **Vue+Vite** project to use :has() in lower versions of Firefox, such as 110.0.
I followed the opetaions in README.md:
1. `npm install css-has-pseudo --save-dev`
2. Use it as a PostCSS plugin: import it and use it in the file "postcss.config.js"
3. initialize cssHasPseudo: use it in the file "App.vue"
`import cssHasPseudo from 'css-has-pseudo/browser';
cssHasPseudo(document);`

It works when I run the project locally with a mock server, but it doesn't work when I build the project and run it with a real server. In the build product, there're ".js-has-pseudo [csstools-has-xxx" in the stylesheet, but there's no "[csstools-has-xxx" attribute added to the elements.
I think the operation "cssHasPseudo(document)" is the most important, but how can it works when building the project?

**Comment by romainmenke** [comment] 2024-11-07 07:10
Hi @Annie972297,

I am unsure what could be the cause of this.

Do you have a project you can share that has this issue?
Something I can run and inspect.

**Comment by romainmenke** [comment] 2024-11-07 13:04
@Annie972297,

Have you checked if there are errors in the browser console about CORS?

See: https://github.com/csstools/postcss-plugins/tree/main/plugins/css-has-pseudo#cors

**Comment by romainmenke** [comment] 2024-11-13 14:31
Closing this issue because of a lack of reply.

@Annie972297 happy to help if you provide more info :)

**Closed by romainmenke** 2024-11-13 14:31 UTC
Labels: waiting on more details
