### ISSUE TITLE
:focus-visible conflicts with :has

### ISSUE THREAD

**Issue by edoardocavazza** [csstools/postcss-plugins#729] opened 2022-11-25 11:57 UTC
### Bug description

Transformation of `:has(:focus-visible)` generates invalid CSS when using postcss-preset-env. Probably, it is a problem with plugins execution order.

### Source CSS

```css
div:has(:focus-visible) {
  outline: solid 2px red;
}
```

### Expected CSS

```css
div[\:has\(\.focus-visible\)] {
  outline: solid 2px red;
}
```

### Actual CSS

```css
div[\:has\(.focus-visible\)] {
  outline: solid 2px red;
}
```
^ note that the `.` in `.focus-visible` is not escaped.

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

Yes

### What plugin are you experiencing this issue on?

PostCSS Preset Env

### Plugin version

7.19.4

### What OS are you experiencing this on?

macOS

### Node Version

v17.9.1

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment] 2022-11-25 12:03
Hi @edoardocavazza,
Thank you for reaching out!

The current plugin version indeed is flawed and doesn't correctly handle these cases.
Changing it however is a breaking change.

We first released an update with a fix as an experimental plugin : https://github.com/csstools/postcss-plugins/tree/main/experimental/css-has-pseudo#how-it-works

And this was later released as a new major version of the regular plugin : https://github.com/csstools/postcss-plugins/tree/postcss-preset-env--v8/plugins/css-has-pseudo#readme

This is not yet included in the current version of `postcss-preset-env` because that would again be breaking.

There is however already an pre-release version : https://github.com/csstools/postcss-plugins/blob/postcss-preset-env--v8/plugin-packs/postcss-preset-env/CHANGELOG.md#800-alpha1-november-14-2022

We are nearing the final chunks of development in the next major for `postcss-preset-env`

**Comment by romainmenke** [comment] 2022-11-25 12:07
duplicate of : https://github.com/csstools/postcss-plugins/issues/320

**Comment by romainmenke** [comment] 2022-11-25 18:30
@edoardocavazza Did this answer your question?

**Comment by edoardocavazza** [comment] 2022-11-25 21:29
Yes, thank you!

**Closed** 2022-11-25 22:31 UTC
Labels: bug, plugins/css-has-pseudo
