### ISSUE TITLE
Allow regressive fallback to 1x for `postcss-image-set-function`

### ISSUE THREAD

**Issue by carlosjeurissen** [csstools/postcss-plugins#493] opened 2022-06-20 17:33 UTC
### What would you want to propose?

Currently using `postcss-image-set-function`, adds several media queries to your CSS. This can easily add up and make the css files too big.

### Suggested solution

The proposed solution is to add a `regression: true` option to `postcss-image-set-function`. Which would omit all the media queries and just add the non-image-set line.

This makes the site still usable (tho less beautiful), yet doesn't unnecessarily bloat the CSS.

In practice:
```
.foo {
  align-items: center;
  background-image: image-set(url(img/test.png) 1x,
                              url(img/test-2x.png) 2x,
                              url(my-img-print.png) 600dpi);
  color: black;
}
```

Would transform into just:
```
.foo {
  align-items: center;
  background-image: url(img/test.png),
  background-image: image-set(url(img/test.png) 1x,
                              url(img/test-2x.png) 2x,
                              url(my-img-print.png) 600dpi);
  color: black;
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [x] I'm willing to open a PR

**Comment by Antonio-Laguna** [comment] 2022-06-20 18:25
@carlosjeurissen thanks for taking the time to report this! I'm not sure this is a way forward

To achieve what you want, given that you already wrote the whole `image-set`, you should be able to just write that `background-image` on top and disable this plugin on postcss-preset-env if you don't want to deal with the amount of media queries it generates. 

Alternatively, you can also use https://github.com/yunusga/postcss-sort-media-queries if you want to combine media queries (though we don't necessarily recommend this plugin)

**Comment by carlosjeurissen** [comment] 2022-06-20 18:43
@Antonio-Laguna Thanks for your swift reply! Of course declaring it yourself is possible. However, the point of postcss and tools like autoprefixer is that you can rely on modern syntax and let it fallback gracefully.

Tho I understand this might not be a priority. Would a PR be welcome? Or do you prefer this option to not be available in general?

**Comment by romainmenke** [comment] 2022-07-09 09:09
@carlosjeurissen We will likely not add this option here as we try to keep plugins as lean as possible.

I was however curious if you could elaborate on this :

> This can easily add up and make the css files too big.

- is there a measurable performance issue caused by this plugin in particular?
- how large is your CSS without this plugin
- how large is your CSS with it?

Knowing more will allow us to make a more informed choice here :)

**Comment by romainmenke** [comment] 2022-08-15 07:47
@carlosjeurissen Going to close this for now.
But feel free to add the requested information above at any time.

We are happy to take another look at this.

**Closed by romainmenke** 2022-08-15 07:47 UTC
Labels: feature request
