### ISSUE TITLE
Postcss-custom-media not working with Next.js

### ISSUE THREAD

**Issue by zhrivodkin** [csstools/postcss-plugins#822] opened 2023-01-31 12:46 UTC
Hello! It seems that `postcss-custom-media` not working with `Next.js` if it being configured accordingly to [their guidelines](https://nextjs.org/docs/advanced-features/customizing-postcss-config) without `importFrom` prop, which one has been deprecated somewhere after 8.0.0 plugin version [when `postcss-preset-env` updated](https://github.com/csstools/postcss-plugins/pull/472/files#diff-af583b4b01ed5acd88459ea671b682c6c4be1f6ff10e91da302f2bcf17466da2R7). Can you please give me an advise what to do? Leave working 8.0.0? Wait for updates?

Thank you.

**Comment by romainmenke** [comment] 2023-01-31 13:08
Hi @zhrivodkin,
Thank you for reaching out.

Do you have a minimal reproduction or a more detail description of "not working"?

As far as we know there is no interaction between `postcss-custom-media` and `Next.js` is itself so this is likely related to how CSS is structured and imported in a `Next.js` project.

**Comment by zhrivodkin** [comment] 2023-02-01 11:21
Hi @romainmenke, thanks for answer, my minimal **working** setup (with css modules) is:
``` js
/* package.json */
...
"next": "^13.1.5",
"react": "^18.2.0",
"@babel/preset-env": "^7.16.11",
"babel-loader": "^8.2.3",
"css-loader": "^6.6.0",
"postcss-loader": "^7.0.2",
"postcss-custom-media": "8.0.0",
...
```
``` css
/* custom-media.css */
@custom-media --mobile (min-width: 428px);
@custom-media --tablet-s (min-width: 768px);
...
```
``` javascript
/* postcss.config.js */
const path = require('path');
module.exports = {
  plugins: [
    ...
    ['postcss-custom-media', {
      importFrom: path.resolve(__dirname, 'src/assets/styles/custom-media.css')
    }]
  ],
};
...
```
``` css
/* timetable.module.css */
.timetable {
  height: 51px;
  margin-top: 3px;

  @media (--tablet-s) {
    height: 60px;
    margin-top: 4px;
  }
}
```
Result:
``` css
@media (min-width: 768px)
.styles_timetable__sxkq2 {
  height: 60px;
  margin-top: 4px;
}
```

And when I update custom-media lib to version 9.1.1, remove `importFrom` option from `postcss.config.js` and import `custom-media.css` to my global styles, no conversion occures. Maybe I need to update some other libs or import my custom media variables directly in every file where I use them?

**Comment by romainmenke** [comment] 2023-02-01 11:29
Hi @zhrivodkin Thank you for this,

Is it possible to put this together in something like stackblitz?
I don't know next, react or css modules, so it is hard for me to create something that will accurately reproduce your issue.

This is important because the plugin does work for different stacks and setups.
To be able to help with your setup we must have something we can test :)

**Comment by djmtype** [comment] 2023-02-03 14:06
I'm using Astro. Being able to use `importFrom` is a big deal. What is the workaround besides not upgrading to postcss-preset-env v8? 

My postcss config: 
```js
const postcssPresetEnv = require("postcss-preset-env");

module.exports = {
  plugins: [
    postcssPresetEnv({
      stage: 0,
      features: {
        "custom-media-queries": {
          importFrom: ["./src/styles/common/queries.css"],
        },
      },
      autoprefixer: true
    })
};
```

**Comment by romainmenke** [comment] 2023-02-07 16:30
@zhrivodkin We have created a new plugin that might resolve your issue : https://www.npmjs.com/package/@csstools/postcss-global-data

Can you check this out and let us know if everything works as expected?

**Comment by romainmenke** [comment] 2023-02-10 16:48
@zhrivodkin Most issues that have been reported to us have been resolved with the addition of this new plugin.

It would be awesome if we could know if this is also fixed or not.

**Comment by romainmenke** [comment] 2023-02-14 19:14
I am assuming this is fixed.
Closing because we haven't received any new info.

**Closed by romainmenke** 2023-02-14 19:14 UTC

**Comment by zhrivodkin** [comment] 2024-02-28 15:51
Yes, problem resolved, thank you very much!
