### ISSUE TITLE
postcss-custom-media: use OnceExit/AtRuleExit instead Once/AtRule

### ISSUE THREAD

**Issue by NikolayMakhonin** [csstools/postcss-plugins#629] opened 2022-09-27 11:11 UTC
### What would you want to propose?

I use `postcss-advanced-variables` which looking for all @import rules and concat them into a single file. But the `postcss-custom-media` handle file before resolving imports and accordingly does not work with all imported files. Usage of OnceExit and AtRuleExit will solve this problem.

### Suggested solution

Use OnceExit/AtRuleExit instead Once/AtRule

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment] 2022-09-27 11:26
@NikolayMakhonin Can you provide a concrete example of input and desired vs. actual output?

To be realistic we will not be able to do this change because just like the current behaviour is not ideal for you it is actually what the ecosystem depends on today.
Changing it would be breaking for everyone else.

It would still be good to know you case in detail.
Maybe there is an alternative we can suggest or maybe there is even a real bug at the root of this.

**Comment by romainmenke** [comment] 2022-10-01 07:57
@NikolayMakhonin Is there anything extra you can share so that we can investigate further?

For an issue like this one it is best if we receive a GitHub repo with a minimal reproduction.

**Comment by romainmenke** [comment] 2022-11-07 18:52
@NikolayMakhonin I am closing this because of a lack of info.
If you can share any more info with us I will re-open.

I am happy to look into this further and spend time fixing a potential bug, but we just need  just a bit more info to confirm the problem.

**Closed by romainmenke** 2022-11-07 18:52 UTC
Labels: feature request
