### ISSUE TITLE
Semicolons being added after `&` nesting rules `postcss-nesting`

### ISSUE THREAD

**Issue by AlbertMarashi** [csstools/postcss-plugins#1150] opened 2023-10-13 00:27 UTC
### Bug description

Semicolons being added after `}` blocks using css nesting, leading to invalid CSS (semicolons not valid after `}` block)

### Source CSS

```css
button {
    display: flex;
    border: 1px solid var(--dark);
    width: 100%;
    justify-content: center;
    height: 100%;
    align-items: center;
    gap: 8px;
    padding: 4px 8px;
    font-size: 14px;
    font-weight: 500;
    &.selected {
        background: rgba(var(--brand-rgb), 0.1);
    }
    &:first-child {
        border-radius: 50px 0 0 50px;
    }
    &:last-child {
        border-radius: 0 50px 50px 0;
    }
}
```

### Expected CSS

```css
button.s-gwue9lYI_bHl{display:flex;border:1px solid var(--dark);width:100%;justify-content:center;height:100%;align-items:center;gap:8px;padding:4px 8px;font-size:14px;font-weight:500;}button.s-gwue9lYI_bHl.selected {
        background: rgba(var(--brand-rgb), 0.1);
    }button.s-gwue9lYI_bHl:first-child {
        border-radius: 50px 0 0 50px;
    }button.s-gwue9lYI_bHl:last-child {
        border-radius: 0 50px 50px 0;
    }.s-gwue9lYI_bHl{}
```

### Actual CSS

```css
button.s-gwue9lYI_bHl{display:flex;border:1px solid var(--dark);width:100%;justify-content:center;height:100%;align-items:center;gap:8px;padding:4px 8px;font-size:14px;font-weight:500;}button.s-gwue9lYI_bHl.selected {
        background: rgba(var(--brand-rgb), 0.1);
    };button.s-gwue9lYI_bHl:first-child {
        border-radius: 50px 0 0 50px;
    };button.s-gwue9lYI_bHl:last-child {
        border-radius: 0 50px 50px 0;
    }.s-gwue9lYI_bHl{}
```

### Does it happen with `npx @csstools/csstools-cli <plugin-name> minimal-example.css`?

- [ ] no

### Extra config

Using SvelteKit, Vite

### What plugin are you experiencing this issue on?

PostCSS Nesting

### Plugin version

^12.0.1

### What OS are you experiencing this on?

Windows

### Node Version

18.17

### Validations

- [X] Follow our [Code of Conduct](https://github.com/csstools/postcss-plugins/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by romainmenke** [comment] 2023-10-13 06:18
Hi @AlbertMarashi,

Thank you for reaching out about this.

I can't seem to be able to replicate this issue in the [playground](https://preset-env.cssdb.org/playground/#eyJzb3VyY2UiOiJidXR0b24ge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tZGFyayk7XG4gICAgd2lkdGg6IDEwMCU7XG4gICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG4gICAgaGVpZ2h0OiAxMDAlO1xuICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgZ2FwOiA4cHg7XG4gICAgcGFkZGluZzogNHB4IDhweDtcbiAgICBmb250LXNpemU6IDE0cHg7XG4gICAgZm9udC13ZWlnaHQ6IDUwMDtcbiAgXG4gICAgJi5zZWxlY3RlZCB7XG4gICAgICAgIGJhY2tncm91bmQ6IHJnYmEodmFyKC0tYnJhbmQtcmdiKSwgMC4xKTtcbiAgICB9XG4gICAgJjpmaXJzdC1jaGlsZCB7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6IDUwcHggMCAwIDUwcHg7XG4gICAgfVxuICAgICY6bGFzdC1jaGlsZCB7XG4gICAgICAgIGJvcmRlci1yYWRpdXM6IDAgNTBweCA1MHB4IDA7XG4gICAgfVxufSIsImNvbmZpZyI6eyJicm93c2VycyI6WyI%2BIDAuMiUgYW5kIG5vdCBkZWFkIl0sIm1pbmltdW1WZW5kb3JJbXBsZW1lbnRhdGlvbnMiOjAsInN0YWdlIjoyLCJsb2dpY2FsIjp7ImlubGluZURpcmVjdGlvbiI6ImxlZnQtdG8tcmlnaHQiLCJibG9ja0RpcmVjdGlvbiI6InRvcC10by1ib3R0b20ifSwiZmVhdHVyZXMiOnsibmVzdGluZy1ydWxlcyI6eyJub0lzUHNldWRvU2VsZWN0b3IiOmZhbHNlfX19fQ%3D%3D) 

We do have code to add semicolons to address this issue : https://github.com/csstools/postcss-plugins/issues/497

Is it possible that another plugin is causing this issue?
What is the output when you disable everything except for `postcss-nesting`?

**Comment by romainmenke** [comment] 2023-10-16 21:20
@AlbertMarashi Have you had a chance to look into this?

To us it seems that the bug lies elsewhere, so I am inclined to close this issue.
Do you have any other info you could share?

**Comment by AlbertMarashi** [comment] 2023-10-16 22:05
@romainmenke Yes I've tried with only `postcss-nesting`. I also attempted to replicate this in the minimal example but wasn't able to replicate it.

I am wondering if it's an issue to do with Svelte or Vite which I am using in my project

```ts
import { sveltekit } from "@sveltejs/kit/vite"
import { defineConfig } from "vite"
import postcssNesting from "postcss-nesting"

export default defineConfig({
    plugins: [sveltekit()],
    css: {
        postcss: {
            plugins: [
                // polyfill for nesting css (not widely supported yet)
                postcssNesting(),
            ],
        },
    }
})
```
This doesn't work

**Comment by AlbertMarashi** [comment] 2023-10-16 22:19
https://github.com/AlbertMarashi/postcss-nesting-bug

Here is a minimal reproducible example demonstrating the issue

**Comment by AlbertMarashi** [comment] 2023-10-16 22:33
```svelte
<div class="foo">
    this should be blue
</div>
<div class="foo bar">
    this should be green
</div>
<style>

div {
    border: 1px solid red;
    padding: 10px;
    &.foo {
        border: 1px solid blue;
    }
    &.bar {
        border: 1px solid green;
    }
}

</style>
```
![image](https://github.com/csstools/postcss-plugins/assets/17972275/97ab7a21-3a22-46a3-a2cf-14ec5e51db67)

**Comment by AlbertMarashi** [comment] 2023-10-16 22:55
I've just opted to use `lightningcss` because it happens to work fine with vite

**Comment by romainmenke** [comment] 2023-10-17 07:58
This is not a bug in `postcss-nesting`.
Some other part of your stack is changing the AST and is adding `ownSemicolon` to rules.

`ownSemicolon` is never added or removed by `postcss-nesting`.
This flag indicates if a rule should have a semicolon at the end.

e.g. `@import 'foo.css';`

I think that Svelte/Vite/... contains some plugin for CSS modules?
And I suspect that this part doesn't support the css nesting spec (yet).

You are obviously free to use any tool you want and whatever works for you is also the best tool ;)

**Comment by romainmenke** [comment] 2023-10-17 08:02
@AlbertMarashi I am a bit surprised to find that you are fully aware that CSS nesting is not supported in Svelte 😕 

I am not sure why you would expect all this to work when you know that Svelte is working on it... https://github.com/sveltejs/svelte/issues/8587#issuecomment-1734059455

I've just spend considerable time trying to pinpoint what is going on and how to fix this issue. You could have given me the background that it simply isn't supported at all in Svelte...

Please be respectful of other peoples time.
Especially when those people create tools for you to use for free.

**Closed by romainmenke** 2023-10-17 08:02 UTC

**Comment by romainmenke** [comment] 2023-10-17 08:11
I've filed the issue in the right place : https://github.com/sveltejs/svelte/issues/9320
